WebShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;
using WebShop.BLL;

namespace WebShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Example
        public ActionResult Index()
        {
            using (var domainModel = new ProductDomainModel())
            {
                var model = domainModel.GetAll();
                return View(model);
            }
        }

        public ActionResult AddOne(ProductPageModel productPM, int[] categories)
        {
            using (var domainModel = new ProductDomainModel())
            {           
                domainModel.Create(productPM, categories);
                return RedirectToAction("Index");
            }
        }
        public ActionResult Changing(long artikul)
        {
            var domainModel = new ProductDomainModel();
            var domainModel1 = new PrCategoryDomainModel();
            Product product = domainModel.GetOne(artikul);
            ProductPageModel PPM = domainModel.ProductPage(artikul);
            ViewBag.Categories = domainModel1.GetAll();
            ViewBag.Hdds = domainModel.GetHdds();
            ViewBag.Videocards = domainModel.GetVCs();
            ViewBag.Mems = domainModel.GetMems();
            ViewBag.Processors = domainModel.GetPrs();
            ViewBag.Categories_FP = domainModel1.GetAll_ForProduct(product);
            return View(PPM);
        }
        [HttpPost]
        public ActionResult Add_Changes(ProductPageModel product, int[] categories, string[] img)
        {
            var domainModel = new ProductDomainModel();
            domainModel.Update(product, categories, img);
            return RedirectToAction("Index");
        }
        //public ActionResult Delete(long artikul)
        //{
        //    var domainModel = new ProductDomainModel();
        //    Product product = domainModel.GetOne(artikul);
        //    domainModel.Delete(product);
        //    return RedirectToAction("Index");
        //}
        public ActionResult Adding()
        {
            var domainModel = new ProductDomainModel();
            var domainModel1 = new PrCategoryDomainModel();
            ProductPageModel product = new ProductPageModel();
            product.img.Add("~/Images/default.png");
            ViewBag.Categories = domainModel1.GetAll();

            ViewBag.Hdds = domainModel.GetHdds();
            ViewBag.Videocards = domainModel.GetVCs();
            ViewBag.Mems = domainModel.GetMems();
            ViewBag.Processors = domainModel.GetPrs();

            return View(product);
        }
        [HttpPost]
        public ActionResult Search(string SearchingString)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            var domainModel = new ProductDomainModel();
            var model = domainModel.GetAll().Where(x => x.Name.Contains(SearchingString));
            return View("Index", model);
        }
        [HttpPost]
        public double Calculate(double cost, double sale)
        {
            if ((cost >= 0) && (cost <= 100000)&&(sale>=0)&&(sale<=100))
            {
                return (cost - (double)((cost * sale) / 100));
            }
            else { return 0; }
        }
    }
}

WebShop/Controllers/ProductsListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.BLL;
using WebShop.Models;
using PagedList.Mvc;
using PagedList;
using Microsoft.AspNet.Identity;

namespace WebShop.Controllers
{
    public class ProductsListController : Controller
    {
        List<ProductInfoModel> list = null;
        Queue<long> prev = new Queue<long>();
        bool isCurrent = true;
        // GET: Products
        public ActionResult Index(int? page, string sortOrder, int? categId, string SearchString,
            string amount, string hdd, string sales, string currentFilter, string minPr, 
            string maxPr, string present, string minHDD, string maxHDD, string freq, string minFreq, 
            string maxFreq, string mem, string maxMem, string minMem, 
            string asus, string acer, string lenovo, string dell, string hp, string other)
        {
            (new CartsController()).CartAmount();
            if (categId != null)
            {
                ViewBag.CategoryItem = (int)categId;
                ViewBag.Category = (int)categId;
            }

            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            ViewBag.CurrentFilter = SearchString;

            using (var domainModel = new ProductDomainModel())
                {
                
                if (list == null && categId == null)
                    list = domainModel.GetProductInfo().ToList();
                else if (list == null && categId != null)
                     list = domainModel.GetProductInfoByCategory((int)categId).ToList();
              
  
                if(list!=null && list.Count > 0)
                {
                    ViewBag.MaxPrice = list.Max(x => x.Sale_cost);
                    ViewBag.MaxHDDSize = list.Max(x=> x.HddSize);
                    ViewBag.MaxMemory = list.Max(x => x.PhysMem);

                    if (!String.IsNullOrEmpty(SearchString))
                    {
                        SearchString = SearchString.ToUpper();
                        list = list.Where(x => x.Name.ToUpper().Contains(SearchString)
                                        || x.Mark.ToUpper().Contains(SearchString)
                                        || x.Cost.ToString().ToUpper().Contains(SearchString)
                                || x.Sale_cost.ToString().ToUpper().Contains(SearchString)).ToList();
                    }
                    if (!String.IsNullOrEmpty(sales))
                    {
                        ViewBag.SalesCheck = "checked";
                        list = list.Where(x => x.Sale > 0).ToList();
                    }
                    if (!String.IsNullOrEmpty(present))
                    {
                        ViewBag.PresentCheck = "checked";
                        list = list.Where(x => x.Amount_store > 0).ToList();
                    }
                    if (!String.IsNullOrEmpty(hdd))
                    {
                        string[] hdds = hdd.Split('-');
                        double min = Convert.ToDouble(hdds[0]);
                        double max = Convert.ToDouble(hdds[1]);
                        list = list.Where(x => x.HddSize >= Convert.ToDouble(min) &&
                                x.HddSize <= Convert.ToDouble(max)).ToList();
                        ViewBag.minHDD = min.ToString();
                        ViewBag.maxHDD = max.ToString();
                    }
                    else if (maxHDD != null || minHDD != null)
                    {
                        ViewBag.maxHDD = ViewBag.MaxHDDSize;
                        ViewBag.minHDD = ViewBag.MinHDDSize;
                        if (minHDD != null)  ViewBag.minHDD = minHDD;
                        if (maxHDD != null) ViewBag.maxHDD = maxHDD;
                        list = list.Where(x => x.HddSize >= Convert.ToDouble(minHDD) &&
                                x.HddSize <= Convert.ToDouble(maxHDD)).ToList();
                    }
                    else
                    {
                        ViewBag.maxHDD = ViewBag.MaxHDDSize;
                        ViewBag.minHDD = ViewBag.MinHDDSize;
                    }
                    if (!String.IsNullOrEmpty(freq))
                    {
                        string[] freqs = freq.Split('-');
                        double min = Convert.ToDouble(freqs[0]);
                        double max = Convert.ToDouble(freqs[1]);
                        list = list.Where(x => x.ProcFreq >= min && x.ProcFreq <= max).ToList();
                        ViewBag.minFreq = min;// min.ToString();
                        ViewBag.maxFreq = max; //.ToString();
                    }
                    else
                    {
                        ViewBag.minFreq = 0; ViewBag.maxFreq = 10;
                        if (minFreq != null) ViewBag.minFreq = minFreq;
                        if (maxFreq != null) ViewBag.maxFreq = maxFreq;
                        list = list.Where(x => x.ProcFreq >= Convert.ToDouble(ViewBag.minFreq) &&
                                x.ProcFreq <= Convert.ToDouble(ViewBag.maxFreq)).ToList();
                    }
                    if (!String.IsNullOrEmpty(mem))
                    {
                        string[] mems = mem.Split('-');
                        double min = Convert.ToDouble(mems[0]);
                        double max = Convert.ToDouble(mems[1]);
                        list = list.Where(x => x.PhysMem >= min && x.PhysMem <= max).ToList();
                        ViewBag.minMem = min;// min.ToString();
                        ViewBag.maxMem = max; //.ToString();
                    }
                    else
                    {
                        ViewBag.minMem = 0; ViewBag.maxMem = ViewBag.MaxMemory;
                        if (minMem != null) ViewBag.minMem = minMem;
                        if (maxMem != null) ViewBag.maxMem = maxMem;
                        list = list.Where(x => x.PhysMem >= Convert.ToDouble(ViewBag.minMem) &&
                                x.PhysMem <= Convert.ToDouble(ViewBag.maxMem)).ToList();
                    }
                    if (!String.IsNullOrEmpty(amount))
                    {
                        string[] amounts = amount.Split('-');
                        double min = Convert.ToDouble(amounts[0]);
                        double max = Convert.ToDouble(amounts[1]);
                        list = list.Where(x => x.Sale_cost >= min && x.Sale_cost <= max).ToList();
                        ViewBag.min = min.ToString();
                        ViewBag.max = max.ToString();
                    }
                    else if (maxPr != null)
                    {
                        ViewBag.min = minPr;
                        ViewBag.max = maxPr;
                        list = list.Where(x => x.Sale_cost >= Convert.ToDouble(minPr) &&
                                x.Sale_cost <= Convert.ToDouble(maxPr)).ToList();
                    }
                    else
                    {
                        ViewBag.max = ViewBag.MaxPrice;
                    }
             //       if (list != null && list.Count > 0)
             //       {
                        bool oth = false;
                        List<string> nb = new List<string>();
                        if (!String.IsNullOrEmpty(asus)) { nb.Add("Asus"); ViewBag.asus = "checked"; }
                        if (!String.IsNullOrEmpty(acer)) { nb.Add("Acer"); ViewBag.acer = "checked"; }
                        if (!String.IsNullOrEmpty(dell)) { nb.Add("Dell"); ViewBag.dell = "checked"; }
                        if (!String.IsNullOrEmpty(hp)) { nb.Add("HP"); ViewBag.hp = "checked"; }
                        if (!String.IsNullOrEmpty(lenovo)) { nb.Add("Lenovo"); ViewBag.lenovo = "checked"; }
                        if (!String.IsNullOrEmpty(other)) { oth = true; ViewBag.other = "checked"; }

                        if (nb.Count > 0 && !oth) list = list.Where(x => nb.Contains(x.Mark)).ToList();
                        else if (oth)
                        {
                            if (!nb.Contains("Asus")) list = list.Where(x => x.Mark != "Asus").ToList();
                            if (!nb.Contains("Acer")) list = list.Where(x => x.Mark != "Acer").ToList();
                            if (!nb.Contains("Dell")) list = list.Where(x => x.Mark != "Dell").ToList();
                            if (!nb.Contains("HP")) list = list.Where(x => x.Mark != "HP").ToList();
                            if (!nb.Contains("Lenovo")) list = list.Where(x => x.Mark != "Lenovo").ToList();
                        }
                        else
                        {
                            ViewBag.asus = "checked";
                            ViewBag.acer = "checked";
                            ViewBag.dell = "checked";
                            ViewBag.hp = "checked";
                            ViewBag.lenovo = "checked";
                            ViewBag.other = "checked";
                        }
                //    }


                    ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) || sortOrder == "Name"
                                            ? "Name desc" : "Name";
                    ViewBag.CostSortParam = sortOrder == "Cost" ? "Cost desc" : "Cost";
                    ViewBag.PopulSortParam = sortOrder == "Popul" ? "Popul desc" : "Popul desc";

                    switch (sortOrder)
                    {
                        case "Name desc":
                            list = list.OrderByDescending(s => s.Name).ToList();
                            break;
                        case "Cost":
                            list = list.OrderBy(s => s.Sale_cost).ToList();
                            break;
                        case "Cost desc":

WebShop/Views/Product/Adding.cshtml
@model WebShop.Models.ProductPageModel
@{
    ViewBag.Title = "Добавление товара";
    Layout = "~/Views/Shared/Wrapper.cshtml";
}
@*<script src="~/Scripts/jquery-ui-1.12.0.js"></script>
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />*@
<h2>@ViewBag.Title</h2>
@*<!DOCTYPE html>

<html>
<head>
    
    <title>Index</title>
</head>
<body>*@
<meta name="viewport" content="width=device-width" />

    
    <fieldset style="height: 100%">
        @*<section id="adding" class="section">*@
            @using (Html.BeginForm("AddOne", "Product", FormMethod.Post))
            {
                @*<div class="form-group">
                    @Html.LabelFor(model => model.Artikul, "Артикул", new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.Artikul)
                        @Html.HiddenFor(model => model.Artikul)
                                        @Html.TextBoxFor(model => model.Artikul, new { @class = "form-control", disabled = "disabled" })
                            </div>
                        </div>*@
                
                    <div class="form-group row">
                    
                        @Html.LabelFor(model => model.img, "Изображение", new { @class = "col-md-2 control-label" })
                        
                       <div class="col-md-10">
                            @{ foreach (var im in Model.img)
                                {              
                                    @Html.TextBoxFor(model => im, new { @class = "form-control", @readonly = "readonly" })
                                }
                            }
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Name, "Имя", new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Mark, "Марка", new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Mark, new { @class = "form-control" })
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="categories" class="col-md-2 control-label">Категории</label>
                        <div class="col-md-10">
                            @{
                                List<WebShop.Models.PrCategoryModel> Categories = ViewBag.Categories;
                                foreach (var c in Categories)
                                {

                                    <label class="checkbox">
                                        <input type="checkbox" name="categories" value="@c.Category_id"> @c.Category
                                    </label>

                                }
                            }
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.HDD_id, "Накопитель", new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.HDD_id, new SelectList(ViewBag.Hdds, "HDD_id", "HDD"))
                            ГБ
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Memory_id, "Оперативная память", new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Memory_id, new SelectList(ViewBag.Mems, "Memory_id", "Memory"))
                            ГБ
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Proc_id, "Процессор", new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Proc_id, new SelectList(ViewBag.Processors, 
                                                        "Proc_id", "ProcessorProducer"))
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.VideoMemory, "Видеокарта", new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Video_id, new SelectList(ViewBag.Videocards,
                                                        "Video_id", "VideoProducer"))
                        </div>
                    </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.Cost, "Цена", new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Cost, new { @class = "form-control", type = "number", min = "0", max = "100000" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.Sale, "Скидка (%)", new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Sale, new { @class = "form-control", type = "number", min = "0", max = "99" })
                                @*@Html.ValidationMessageFor(model => (model.Sale<0)||(model.Sale>=100),"Скидка вариируется от 0 до 99 %")*@
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.Sale_cost, "Цена со скидкой", new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Sale_cost, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.Amount_store, "Количество на складе", new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Amount_store, new { @class = "form-control", type = "number", min = "0", max = "100000" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.Visible, "Видимость на сайте", new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.CheckBoxFor(model => model.Visible, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.Information, "Информация", new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Information, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.Popularity, "Популярность", new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Popularity, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <input type="submit" value="Добавить" />
                        </div>
                        }


</fieldset>
                    <script type="text/javascript">
                        $("#Cost").focusout(function () {

                            var url = "@Url.Action("Calculate"/*имя экшина*/, "Product"/*имя контроллера*/)";
                            var Cost = document.getElementById("Cost").value;//$('div:eq(4)').val();
                            var Sale = document.getElementById("Sale").value;
                            var Result;
                            $.ajax({
                                type: "POST",
                                data: { "cost": Cost, "sale": Sale },
                                url: url,
                                success: function (result) {
                                    $('#Sale_cost').attr('value', result);
                                }
                            });
                        });
                    </script>
                    <script type="text/javascript">
                        $("#Sale").focusout(function () {

                            var url = "@Url.Action("Calculate"/*имя экшина*/, "Product"/*имя контроллера*/)";
                            var Cost = document.getElementById("Cost").value;//$('div:eq(4)').val();
                            var Sale = document.getElementById("Sale").value;
                            var Result;
                            $.ajax({
                                type: "POST",
                                data: { "cost": Cost, "sale": Sale },
                                url: url,
                                success: function (result) {
                                    $('#Sale_cost').attr('value', result);
                                }
                            });
                        });
                    </script>
                    @*</section>*@
                    

    @*<div class="col-md-4">
        
        </div>*@
@*<section id="information">
    <p>Тут будет какая-то инструкция</p>
</section>*@
@*</body>
</html>*@

WebShop/Views/Product/Index.cshtml
@model IEnumerable<WebShop.Models.Product>
@{
    ViewBag.Title = "Список товаров";
    
    //Layout = "~/Views/Shared/Wrapper.cshtml";
}
<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.css">

<!-- jQuery -->
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>

<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.js">
</script>


<h2>@ViewBag.Title</h2>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    
</head>
<body>
    @*@{
            using (var domainModel = new WebShop.DAL.)
            {
                var list = domainModel.GetAll();
                foreach (var item in list)
                {
                    string name = item.Category;
                    var id = item.Category_id;
                    <li>
                        @Html.ActionLink(name, "Index", "Home")
                          Use this to pass category of product to code:
                        @Html.ActionLink(name, "Index", "ProductsList", new { page = 1, sortOrder = "", categId = id },
                                   new { @class = ViewBag.CategoryItem == id ? "selected" : null })
                    </li>
                }
            }
        }*@
    @{ var domainModel = new WebShop.DAL.ProductCategory();}
    <p>
        @Html.ActionLink("Добавить товар", "Adding", "Product")
    </p>
    <div style="width:100%; margin:0 auto;">
        <table id="products">
            <thead>
                <tr>
                    <th>
                        Имя
                    </th>
                    <th>
                        Марка
                    </th>
                    @*<th>
                        Категория
                    </th>*@
                    <th>
                        Цена
                    </th>
                    <th>
                        Скидка
                    </th>
                    <th>
                        Цена со скидкой
                    </th>
                    <th>
                        Количество
                    </th>
                    <th>
                        Видимость
                    </th>
                    <th>
                        Популярность
                    </th>
                    <th>
                        Действие
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td name="Name">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td name="Mark">
                            @Html.DisplayFor(modelItem => item.Mark)
                        </td>
                        @*<td>
    @{ var domainModel1 = new WebShop.BLL.CategoryDomainModel();
            var categories = domainModel1.GetAll(item);}
        @Html.DisplayFor(modelItem=> domainModel1, categories)
        @foreach (var cat in item.Categories)
        {
            @Html.DisplayFor(modelItem => cat.Category)<text>,</text>
        }
                        </td>*@
                        <td name="Cost">
                            @Html.DisplayFor(modelItem => item.Cost)
                        </td>
                        <td name="Sale">
                            @Html.DisplayFor(modelItem => item.Sale)
                        </td>
                        <td name="Sale_cost">
                            @Html.DisplayFor(modelItem => item.Sale_cost)
                        </td>
                        <td name="Amount">
                            @Html.DisplayFor(modelItem => item.Amount_store)
                        </td>
                        <td name="Visible">
                            @Html.DisplayFor(modelItem => item.Visible)
                        </td>
                        <td name="Popularity">
                            @Html.DisplayFor(modelItem => item.Popularity)
                        </td>
                        <td>
                            @Html.ActionLink("Редактировать", "Changing", "Product", new { artikul = item.Artikul }, new { style = "color:red" }) 
                            @*@Html.ActionLink("Удалить", "Delete", "Product", new { artikul = item.Artikul }, new { style = "color:black" })*@
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>

    <style>
        tr.even {
            background-color: #F5F5F5 !important;
        }
    </style>
    @* Load datatable css *@
    <link href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css" rel="stylesheet" />
    @* Load datatable js *@
    @section Scripts{
        <script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
        <script>

            $(document).ready(function () {
                $('#products').DataTable({
                });
            });
        </script>
    }
</body>
</html>

WebShop/Views/Product/Search.cshtml
@model WebShop.Models.Product
@{
    ViewBag.Title = "Я нашел!";
    Layout = "~/Views/Shared/Wrapper.cshtml";
}

<h2>@ViewBag.Title</h2>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <table class="table">
        <tr>
            <th>
                <div>@Html.DisplayFor(modelItem => Model.Name,"Имя")</div>
            </th>
            <th>
                <div>@Html.DisplayFor(modelItem => Model.Mark, "Марка")</div>
            </th>
            <th>
                <div>@Html.DisplayFor(modelItem => Model.Cost, "Цена")</div>
            </th>
            <th>
                <div>@Html.DisplayFor(modelItem => Model.Sale, "Скидка")</div>
            </th>
            <th>
                <div>@Html.DisplayFor(modelItem => Model.Sale_cost, "Цена со скидкой")</div>
            </th>
            <th>
                <div>@Html.DisplayFor(modelItem => Model.Amount_store, "Количество")</div>
            </th>
            <th>
                <div>@Html.DisplayFor(modelItem => Model.Visible, "Видимость")</div>
            </th>
            <th>
                <div>@Html.DisplayFor(modelItem => Model.Popularity, "Популярность")</div>
            </th>
            <th>
                Действие
            </th>
            <th></th>
        </tr>

        @*@{var item = Model; }

            < tr >
                < td >
                    @Html.DisplayFor(modelItem => item.Name)
                </ td >
                < td >
                    @Html.DisplayFor(modelItem => item.Mark)
                </ td >
                < td >
                    @Html.DisplayFor(modelItem => item.Cost)
                </ td >
                < td >
                    @Html.DisplayFor(modelItem => item.Sale)
                </ td >
                < td >
                    @Html.DisplayFor(modelItem => item.Sale_cost)
                </ td >
                < td >
                    @Html.DisplayFor(modelItem => item.Amount_store)
                </ td >
                < td >
                    @Html.DisplayFor(modelItem => item.Visible)
                </ td >
                < td >
                    @Html.DisplayFor(modelItem => item.Popularity)
                </ td >
                @*<td>
                    @Html.ActionLink("Редактировать", "Changing", "Product", new { artikul = item.Artikul }, new { style = "color:red" }) |
                    @Html.ActionLink("Удалить", "Delete", "Product", new { artikul = item.Artikul }, new { style = "color:black" })
                </td>
            </ tr >*@
        
            

    </table>
</body>
</html>