WebShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using WebShop.BLL;
using WebShop.Models;
using System.Net;
using System.Net.Mail;
using System.Net.Sockets;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;

namespace WebShop.Controllers
{
    public class OrderController : Controller
    {
        //public ActionResult Update(OrderModel order, string message_about_status)
        //{
        //    SendEmailaboutStatus(order, message_about_status);
        //    using (var orderForm = new OrderDomainModel())
        //    {
        //        return View(orderForm.GetAll());
        //    }
        //}
        public ActionResult AllOrders()
        {
            using (var orderForm = new OrderDomainModel())
            {
                return View(orderForm.GetAll());
            }
        }
        public ActionResult GoToCarts(long Order_id)
        {
            using (var domainModel = new ProductDomainModel())
            {
                var model = domainModel.GetAll();
            
                using (var cartsdm = new CartsDomainModel())
            {
                    ViewBag.Products = model;
                return View(cartsdm.GetByOrderId(Order_id));
            }
            }
        }

        public ActionResult Login()
        {
            return RedirectToAction("Login", "Account", new { returnUrl = Request.UrlReferrer.ToString() });
        }

        [HttpGet]
        public ActionResult OrderForm()
        {
            List<Int64> ids = new List<long>();
            OrderFormModel orderForm = new OrderFormModel();
            if (TempData["ids"]!=null)
            {
                ids = TempData["ids"] as List<Int64>;
                TempData["ids"] = ids;
            }

            var db = new ApplicationDbContext();
            string userId;

            if (User.Identity.IsAuthenticated)
            {
                userId = User.Identity.GetUserId();
                var user = db.Users.Where(x => x.Id == userId).FirstOrDefault();
                orderForm.Surname = user.Surname;
                orderForm.Name = user.Name;
                orderForm.Address = user.Country + " " + user.City;
                orderForm.Phone = user.Phone;
                orderForm.Email = user.Email;
            }
            orderForm.Cart_ids = new List<long>();
            orderForm.Cart_ids = ids;
            using (var domainModel = new CartsDomainModel())
            {
                orderForm.OrderSum = domainModel.CalcOrderSum(ids);
            }
            return View(orderForm);
        }

        [HttpPost]
        public ActionResult OrderForm(OrderFormModel order)
        {
            if (!ModelState.IsValid)
            {
                using (var domainModel = new CartsDomainModel())
                {
                    order.OrderSum = domainModel.CalcOrderSum(order.Cart_ids);
                }
                return View(order);
            }
            using (var domainModel = new CartsDomainModel())
            {
                if (!domainModel.AddOrderForm(order))
                {
                    ViewBag.Error = "К сожалению, при отправке данных в БД произошла ошибка."+ 
                        " Попробуйте повторить отправку формы";
                    return View(order);
                }
            }
            /* 
              I don`t low Amount_store, increase Popularity of product, set OrderDate - do this on admin page
            */
            (new CartsController()).CartAmount();
            TempData["OrderOK"] = "Ваш заказ будет обработан администраторами в ближайшее время. " +
                "Спасибо, что выбрали наш магазин!";

            SendEmail(order);
            return RedirectToAction("Index", "Home");
        }

        public bool SendEmail(OrderFormModel order)
        {
            string[] shoppingList;
            using (var domainModel = new CartsDomainModel())
            {
                order.OrderSum = domainModel.CalcOrderSum(order.Cart_ids);
                shoppingList = domainModel.getShoppingList(order.Cart_ids);
            }
            string OurName = "Интернет-магазин 'КомпМаг'";
            string OurEmail = "katerinaglinskaya96@gmail.com";
            string OurMess = string.Format("<p>Вы оформили заказ в нашем магазине на сумму {0} грн. " +
                "Наши сотрудники позвонят вам, как только обработают заказ. Обработка заказа " +
                "занимает в среднем 2 дня. Спасибо, что выбрали наш магазин! </p>" +
                "<p>Список заказанных товаров:</p>", order.OrderSum);
            foreach(string s in shoppingList)
            {
                OurMess += "<p>" + s + "</p>";
            }
            var body = "<p>Email От: {0} ({1})</p><p> Здравствуйте, {2}!</p><p>{3}</p>";
            var message = new MailMessage();
            message.To.Add(new MailAddress(order.Email));
            message.From = new MailAddress(OurEmail);
            message.Subject = "Оформление заказа в Интеренет-магазине 'КомпМаг'";
            message.Body = string.Format(body, OurName, OurEmail, 
                order.Name + " " + order.Surname, OurMess);
            message.IsBodyHtml = true;
            try
            {
                using (var smtp = new SmtpClient())
                {
                    smtp.Send(message);
                    
                }
                return true;
            }
            catch
            {
                return false;
            }
        }
        public bool SendEmailaboutStatus(OrderModel order, string message_about_status)
        {
            //string[] shoppingList;
            //using (var domainModel = new CartsDomainModel())
            //{
            //    order.OrderSum = domainModel.CalcOrderSum(order.Cart_ids);
            //    shoppingList = domainModel.getShoppingList(order.Cart_ids);
            //}
            string OurName = "Интернет-магазин 'КомпМаг'";
            string OurEmail = "katerinaglinskaya96@gmail.com";
            string OurMess = message_about_status;
            //foreach (string s in shoppingList)
            //{
            //    OurMess += "<p>" + s + "</p>";
            //}
            var body = "<p>Email От: {0} ({1})</p><p> Здравствуйте, {2}!</p><p>{3}</p>";
            var message = new MailMessage();
            message.To.Add(new MailAddress(order.Email));
            message.From = new MailAddress(OurEmail);
            message.Subject = "Оформление заказа в Интеренет-магазине 'КомпМаг'";
            message.Body = string.Format(body, OurName, OurEmail,
                order.Name + " " + order.Surname, OurMess);
            message.IsBodyHtml = true;
            try
            {
                using (var smtp = new SmtpClient())
                {
                    smtp.Send(message);

                }
                return true;
            }
            catch
            {
                return false;
            }
        }

    }
}

WebShop/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;
using WebShop.BLL;

namespace WebShop.Controllers
{
    public class PictureController : Controller
    {
        // GET: Picture
        public ActionResult Index()
        {
            var domainModel = new BannerDomainModel();
            var domainmodel_products = new ProductDomainModel();
            ViewBag.Products = domainmodel_products.GetAll();
            var image_list = domainModel.GetAll();
            return View(image_list);
        }
        [HttpPost]
        public ActionResult Add(HttpPostedFileBase upload, long artikul)
        {
            if (upload != null)
            {
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Images/" + fileName));

                var domainModel = new BannerDomainModel();
                BannerModel bm = new BannerModel();
                bm.Artikul = artikul;
                bm.Image_path = "~/Images/" + fileName;
                bm.Image_id = domainModel.GetAll().Last().Image_id;
                domainModel.Create(bm);
                // удаляем дефолтный рисунок
                var def = domainModel.GetAll().Where(x => x.Image_path == "~/Images/default.png" &&
                            x.Artikul == bm.Artikul);
                if (def != null && def.Count()>0) domainModel.Delete(def.FirstOrDefault().Image_id);
            }
            return RedirectToAction("Index");
        }
    }
}

WebShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;
using WebShop.BLL;

namespace WebShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Example
        public ActionResult Index()
        {
            using (var domainModel = new ProductDomainModel())
            {
                var model = domainModel.GetAll();
                return View(model);
            }
        }

        public ActionResult AddOne(ProductPageModel productPM, int[] categories)
        {
            using (var domainModel = new ProductDomainModel())
            {           
                domainModel.Create(productPM, categories);
                return RedirectToAction("Index");
            }
        }
        public ActionResult Changing(long artikul)
        {
            var domainModel = new ProductDomainModel();
            var domainModel1 = new PrCategoryDomainModel();
            Product product = domainModel.GetOne(artikul);
            ProductPageModel PPM = domainModel.ProductPage(artikul);
            ViewBag.Categories = domainModel1.GetAll();
            ViewBag.Hdds = domainModel.GetHdds();
            ViewBag.Videocards = domainModel.GetVCs();
            ViewBag.Mems = domainModel.GetMems();
            ViewBag.Processors = domainModel.GetPrs();
            ViewBag.Categories_FP = domainModel1.GetAll_ForProduct(product);
            return View(PPM);
        }
        [HttpPost]
        public ActionResult Add_Changes(ProductPageModel product, int[] categories, string[] img)
        {
            var domainModel = new ProductDomainModel();
            domainModel.Update(product, categories, img);
            return RedirectToAction("Index");
        }
        //public ActionResult Delete(long artikul)
        //{
        //    var domainModel = new ProductDomainModel();
        //    Product product = domainModel.GetOne(artikul);
        //    domainModel.Delete(product);
        //    return RedirectToAction("Index");
        //}
        public ActionResult Adding()
        {
            var domainModel = new ProductDomainModel();
            var domainModel1 = new PrCategoryDomainModel();
            ProductPageModel product = new ProductPageModel();
            product.img.Add("~/Images/default.png");
            ViewBag.Categories = domainModel1.GetAll();

            ViewBag.Hdds = domainModel.GetHdds();
            ViewBag.Videocards = domainModel.GetVCs();
            ViewBag.Mems = domainModel.GetMems();
            ViewBag.Processors = domainModel.GetPrs();

            return View(product);
        }
        [HttpPost]
        public ActionResult Search(string SearchingString)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            var domainModel = new ProductDomainModel();
            var model = domainModel.GetAll().Where(x => x.Name.Contains(SearchingString));
            return View("Index", model);
        }
        [HttpPost]
        public double Calculate(double cost, double sale)
        {
            if ((cost >= 0) && (cost <= 100000)&&(sale>=0)&&(sale<=100))
            {
                return (cost - (double)((cost * sale) / 100));
            }
            else { return 0; }
        }
    }
}

WebShop/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using WebShop.Models;
using System.Web.Security;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Globalization;
using System.Security.Claims;
using System.Threading.Tasks;

namespace WebShop.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        [Authorize(Roles ="superadmin")]
        public ActionResult Index()
        {
            var db = new ApplicationDbContext();
            //ViewBag.item = db.Users.ToList();
            var model = db.Users.ToList();
            List<UserWrapper> UserWrappers = new List<UserWrapper>();
            foreach (var user in model)
            {
                UserWrappers.Add(new UserWrapper { appUser = user, CurrentRole = user.Roles.FirstOrDefault().RoleId });
            }
            return View(UserWrappers);
        }
        [Authorize(Roles = "admin")]
        public ActionResult Index_for_admin()
        {
            var db = new ApplicationDbContext();
            var model = db.Users.ToList();
            List<UserWrapper> UserWrappers = new List<UserWrapper>();
            foreach (var user in model)
            {
                UserWrappers.Add(new UserWrapper { appUser = user, CurrentRole = user.Roles.FirstOrDefault().RoleId });
            }
            return View(UserWrappers);
        }
        [HttpPost]
        [Authorize(Roles = "superadmin")]
        public string Update(string email, string status_new)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            ApplicationUserManager userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(db));
            UserWrapper uw = new UserWrapper();
            
            string RoleName = db.Roles.Where(x=>x.Id==status_new).First().Name;
            foreach (var i2 in userManager.Users.ToList())
            {
                uw.appUser = i2;
                uw.CurrentRole = i2.Roles.First().RoleId;
                if (i2.Email == email)
                {
                        string RoleName1 = db.Roles.Where(x => x.Id == uw.CurrentRole).First().Name;
                        userManager.RemoveFromRole(i2.Id, RoleName1); // я не уверена что тут должен быть RoleId - ПРОВЕРЬ ПЛИЗ
                    userManager.AddToRole(i2.Id, RoleName); // возможно тут не RoleName, а RoleId
                }
            }
                
            db.SaveChanges();
            return ("Изменения внесены!");
        }
    }
}

WebShop/Views/Shared/MainMenu.cshtml
@{
    Layout = null;
}

<div class="menu">
    <ul class="menu_items clearfix">
        
        <li>@Html.ActionLink("Главная", "Index", "Home", null, 
           new { @class = ViewBag.MenuItem == "Main" ? "selected" : null})
             </li>
        <li>
            @Html.ActionLink("Компьютеры", "Index", "ProductsList", null, 
           new { @class = ViewBag.MenuItem == "Products" ? "selected" : null })
            <ul>
                @{
                    using (var domainModel = new WebShop.BLL.PrCategoryDomainModel())
                    {
                        var list = domainModel.GetAll();
                        foreach (var item in list)
                        {
                            string name = item.Category;
                            var id = item.Category_id;
                            <li>
                                @*@Html.ActionLink(name, "Index", "Home")*@
                               @*  Use this to pass category of product to code: *@
                                @Html.ActionLink(name, "Index", "ProductsList", new {page = 1, sortOrder = "",
                               categId = id, currentFilter = ViewBag.CurrentFilter,
                               minPr = ViewBag.min,
                               maxPr = ViewBag.max,
                               sales = ViewBag.SalesCheck,
                               present = ViewBag.PresentCheck,
                               minHDD = ViewBag.minHDD,
                               maxHDD = ViewBag.maxHDD,
                               minFreq = ViewBag.minFreq,
                               maxFreq = ViewBag.maxFreq,
                               minMem = ViewBag.minMem,
                               maxMem = ViewBag.maxMem,
                               acer = ViewBag.acer,
                               asus = ViewBag.asus,
                               lenovo = ViewBag.lenovo,
                               dell = ViewBag.dell,
                               hp = ViewBag.hp,
                               other = ViewBag.other
                           },
                               new { @class = ViewBag.CategoryItem == id ? "selected" : null }) 
                            </li>
                        }
                    }
                }
            </ul>
        </li>

        <li>@Html.ActionLink("О магазине", "About", "Home", null,
            new { @class = ViewBag.MenuItem == "About" ? "selected" : null })</li>
        <li>@Html.ActionLink("Оплата и доставка", "Delivery", "Home", null,
            new { @class = ViewBag.MenuItem == "Delivery" ? "selected" : null })</li>
        <li>@Html.ActionLink("Акции", "Sales", "Home", null,
            new { @class = ViewBag.MenuItem == "Sales" ? "selected" : null })</li>
    </ul>
</div>

WebShop/Views/Shared/Main_menu_admin.cshtml
@{
    Layout = null;
}

<div class="menu">
    <ul class="menu_items clearfix">
        @{if (User.IsInRole("superadmin"))
            { 
        <li>@Html.ActionLink("Главная", "Index", "User")</li>
            }
            else
            {
                <li>@Html.ActionLink("Главная", "Index_for_admin", "User")</li>
            }
        }
             
        <li>
            @Html.ActionLink("Товары", "Index", "Product")
        </li>
        <li>
            @Html.ActionLink("Заказы", "AllOrders", "Order")
        </li>
        <li>
            @Html.ActionLink("Изображения", "Index", "Picture")
        </li>
        <li>
            @Html.ActionLink("О нас", "EditAll", "Home")
        </li>
        @*<li>@Html.ActionLink("О магазине", "About", "Home")</li>
    <li>@Html.ActionLink("Оплата и доставка", "Delivery", "Home")</li>
    <li>@Html.ActionLink("Акции", "Sales", "Home")</li>*@
    </ul>
</div>

WebShop/Views/Shared/Wrapper.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/styles.css">
    
    @*<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>*@

  @*  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>*@
    @*  <script type="text/javascript" src="~/Scripts/click-carousel.js"></script>*@

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <title>InternetShop</title>
</head>
<body>
    <div class="wrapper">
            <header>
               @*Хедер сайта*@
                <a href="@Url.Action("Index","Home") ">
                    <img class="logo" src="~/Images/logo.png" alt="Logo"/>
                </a>

                @*<div class="login">
                    <a href="@Url.Action("Index","Home") "> 
                        Вход/Регистрация
                    </a>
                    
                </div>*@
                   
                <div class="login">
                    @Html.Partial("_LoginPartial")
                    
                </div>
             </header>
        
        @if (User.IsInRole("superadmin")|| User.IsInRole("admin"))
        {
            @Html.Partial("Main_menu_admin");
        }
        else
        {
            @Html.Partial("MainMenu");
        }
        <div class="content clearfix">
            @RenderBody()
        </div>

            

        <footer>
            <div class="address">
              
                <h5>   Нас можно найти: </h5>
                <p>
                    ул. Центральная 54А, Киев <br />
                    87654 Украина <br />
                </p>
            </div>

            <div class="contacts">
                <h5>    Свяжитесь с нами: </h5>
                <p>
                    Тел. +38 (095) 848 48 48 <br />
                    Тел. +38 (044) 848 48 48 <br />
                </p>
            </div>

            <div class="footermenu">
                <h5>    Вам может быть интересно: </h5>
                <p>
                    <a href="@Url.Action("Index", "Home")">Главная >> </a> / <a href="@Url.Action("Login", "Account")">Вход >> </a> <br />
                    <a href="@Url.Action("Index", "ProductsList")">Товары >> </a> / <a href="@Url.Action("Delivery", "Home")">Оплата и доставка >> </a> <br />
                    <a href="@Url.Action("About", "Home")">О нас >> </a> / <a href="@Url.Action("Sales", "Home")">Акции >> </a> 
                </p>
            </div>

            <div class="social" clearfix>
                <h5>    Мы в соцсетях: </h5>
                <p>
                    <a target="_blank" href="https://www.facebook.com"><img src="~/Images/facebook.png" alt="Facebook"/></a>
                    <a target="_blank" href="https://twitter.com/?lang=ru"><img src="~/Images/twitter.png" alt="Twitter" /></a>
                    <a target="_blank" href="https://new.vk.com"><img src="~/Images/vk.png"alt="Vkontakte"/></a>
                </p>
            </div>
            <p class="copy">
                &copy; Все права сохранены
            </p>
            
        </footer>
    </div>
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

WebShop/Views/Shared/Wrapper2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/styles.css">

    @*<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>*@

    @*  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>*@
    @*  <script type="text/javascript" src="~/Scripts/click-carousel.js"></script>*@

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <title>InternetShop</title>
</head>
<body>
    <div class="wrapper">
        <header>
            @*Хедер сайта*@
            <a href="@Url.Action("Index","Home") ">
                <img class="logo" src="~/Images/logo.png" alt="Logo" />
            </a>

            @*<div class="login">
                    <a href="@Url.Action("Index","Home") ">
                        Вход/Регистрация
                    </a>

                </div>*@

            <div class="login">
                @Html.Partial("_LoginPartial")

            </div>
        </header>


        @Html.Partial("Main_menu_admin");
        <div class="content">
            @RenderBody()
        </div>



        <footer>
            <div class="address">

                <h5>   Нас можно найти: </h5>
                <p>
                    ул. Центральная 54А, Киев <br />
                    87654 Украина <br />
                </p>
            </div>

            <div class="contacts">
                <h5>    Свяжитесь с нами: </h5>
                <p>
                    Тел. +38 (095) 848 48 48 <br />
                    Тел. +38 (044) 848 48 48 <br />
                </p>
            </div>

            <div class="footermenu">
                <h5>    Вам может быть интересно: </h5>
                <p>
                    <a href="@Url.Action("Index", "Home")">Главная >> </a> / <a href="@Url.Action("Login", "Account")">Вход >> </a> <br />
                    <a href="#">Товары >> </a> / <a href="@Url.Action("Delivery", "Home")">Оплата и доставка >> </a> <br />
                    <a href="@Url.Action("About", "Home")">О нас >> </a> / <a href="@Url.Action("Sales", "Home")">Акции >> </a>
                </p>
            </div>

            <div class="social" clearfix>
                <h5>    Мы в соцсетях: </h5>
                <p>
                    <a href="https://www.facebook.com"><img src="~/Images/facebook.png" width="40" alt="Facebook" /></a>
                    <a href="https://twitter.com/?lang=ru"><img src="~/Images/twitter.png" width="40" alt="Twitter" /></a>
                    <a href="https://new.vk.com"><img src="~/Images/vk.png" width="40" alt="Vkontakte" /></a>
                </p>
            </div>
            <p class="copy">
                &copy; Все права сохранены
            </p>

        </footer>
    </div>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>